Numpy Basics

In [ ]:
#creating array from list
arr=["Jeyaveeran","Vignesh","Mani",10,20]
print(arr)
#Modifying array from list
arr[0]="M.Sc"
print(arr)
#indexing
arr=["Jeyaveeran","Vignesh","Mani",10,20]
print(arr[1:3])

['Jeyaveeran', 'Vignesh', 'Mani', 10, 20]
['M.Sc', 'Vignesh', 'Mani', 10, 20]
['Vignesh', 'Mani']


In [ ]:
#Find min,max and mean
arr1=[10,20,30,40,50]
print("minimum value of arr1 is:",min(arr1))
#Max value
arr2=[100,200,300,400,500]
print("maximum value of arr2 is:",max(arr2))
#mean value
import numpy as np
arr=[10,20,2,7,8,9]
print("arr:",arr)
print("mean of arr:",np.mean(arr))

minimum value of arr1 is: 10
maximum value of arr2 is: 500
arr: [10, 20, 2, 7, 8, 9]
mean of arr: 9.333333333333334


In [ ]:
#Reshaping and flattening an array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

#Flattening an array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6]


In [ ]:
#create array 1to10
arr=[1,2,3,4,5,6,7,8,9,10]
print(arr)

#Reverse
arr=[1,2,3,4,5,6,7,8,9,10]
arr.reverse()
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
#Create two 2x2 array and stack them vertically and horizontally
import numpy as np
x1=np.array([[10,20,30],[50,60,70]])
x2=np.array([[90,100,110],[130,140,150]])

#stack the array vertically and horizontally
xarray=np.vstack((x1,x2))
yarray=np.hstack((x1,x2))
print(xarray)
print(yarray)

[[ 10  20  30]
 [ 50  60  70]
 [ 90 100 110]
 [130 140 150]]
[[ 10  20  30  90 100 110]
 [ 50  60  70 130 140 150]]


In [ ]:
#convert a 1D array of size 9 into 3x3 matrix
import numpy as np
x=np.array([10,20,30,40,50,60,80,50,40])
arr=x.reshape(3,3)
print(arr)

[[10 20 30]
 [40 50 60]
 [80 50 40]]
